#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

echo "Admin user: ${ADMIN_USER}"
python manage.py run_huey --flush-locks &

python manage.py runserver_plus 0.0.0.0:8000
